### ISSUE TITLE
How long does EETQ take to install? No progress

### ISSUE THREAD

**Issue by RoadTLife** [Qcompiler/QComplier#1]
I tried to install EETQ but got stuck without any information.

```
cd EETQ
python setup.py install
```
![image](https://github.com/user-attachments/assets/3da9ce17-d718-4d30-948f-a62461fa8ef1)

**Comment by Qcompiler** [comment]
Hello! It would take about 30minutes to 60minutes.  ^_^ Thank you!

**Comment by Qcompiler** [comment]
Hello! It would take about 30minutes to 60minutes.  ^_^ Thank you!
