### ISSUE TITLE
‘__syncthreads’ was not declared in this scope

### ISSUE THREAD

**Issue by Godlovecui** [Qcompiler/QComplier#3]
nvcc version: 12.5
cd quantkernel; python setup.py install
![image](https://github.com/user-attachments/assets/a71a17b6-f4b5-4220-95b3-fd50befcb923)
how to fix it? thank you!
@ucascnic

**Comment by Qcompiler** [comment]
Hello, the kernel was not tested on nvcc higher than 12.4, now I will try to reproduce the problem.

**Comment by Godlovecui** [comment]
> Hello, the kernel was not tested on nvcc higher than 12.4, now I will try to reproduce the problem.

I use this docker image: nvcr.io/nvidia/pytorch:24.07-py3, Thank you very much~

**Comment by Qcompiler** [comment]
Hello.  Looks related to https://github.com/NVIDIA/cccl/issues/1373
We have reproduced the problems and fixed the bugs with add `-DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CPP` in quantkernel/setup.py. https://github.com/Qcompiler/QComplier/commit/c6390a4ccf63f9546f4b7cb50ba7a3ebe8cec36d

And now it could be compiled successfully in nvcr.io/nvidia/pytorch:24.07-py3
Thanks a lot for your report!
