### ISSUE TITLE
undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE

### ISSUE THREAD

**Issue by Godlovecui** [Qcompiler/QComplier#4]
hello, I use RTX4090, CC is 8.9,
cuda version: 12.2
it raise below error:
![image](https://github.com/user-attachments/assets/26d1d7c6-399c-490d-8c6d-d65b4f2f14e3)

how to fix? Thank you!

@ucascnic 
@Qcompiler

**Comment by Qcompiler** [comment]
Hello, I have tested the ` import mixlib` with GCC=12.2 Torch=2.4.0 CUDA =12.4 in RTX4090 . And I did not reproduce the problem. 
May I ask the Python version and Pytorch Version of your environment ?

**Comment by Godlovecui** [comment]
python:  3.10.12
torch: 2.4.0+cu121
gcc:  11.4.0
cuda: 12.2

I use this docker image: nvcr.io/nvidia/pytorch:23.10-py3, 
Thank you~ @Qcompiler

**Comment by Qcompiler** [comment]
Hello! This issue is relate to https://github.com/Qcompiler/QComplier/issues/3
And we have updated the setup.py in `https://github.com/Qcompiler/QComplier/commit/c6390a4ccf63f9546f4b7cb50ba7a3ebe8cec36d`
And now we could import mixlib in this docker image: nvcr.io/nvidia/pytorch:23.10-py3
