### ISSUE TITLE
RuntimeError: [FT][ERROR] Unsupported Arch Assertion fail

### ISSUE THREAD

**Issue by Godlovecui** [Qcompiler/QComplier#5]
It will fail in H100, 
`File "/workspaces/QComplier/mixquant/quantize/mixquant.py", line 121, in _apply_quant
    qweight, q_scale_col = quant_weights(int8_weight_cpu, torch.int8, False)
RuntimeError: [FT][ERROR] Unsupported Arch Assertion fail: /workspaces/QComplier/EETQ/csrc/cutlass_kernels/cutlass_preprocessors.cc:125`

The reason is that EETQ does not support cc>=9.0, so how to quantize the model in H100?
https://github.com/NetEase-FuXi/EETQ/blob/main/csrc/cutlass_kernels/cutlass_preprocessors.cc#L113
@Qcompiler 
Thank you~

**Comment by Qcompiler** [comment]
hello, please download the latested EETQ from  https://github.com/Qcompiler/MixQ_Tensorrt_LLM/tree/main/EETQ
which supports  sm90 in this project ~
I will upgrade the file~ thanks a lot
